//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_PRODUCTOS
    {
        [Required]
        [Display(Name = "Id")]
        public int ID_PRODUCTO { get; set; }
        [Required]
        [Display(Name = "Descripcion")]
        public string DESC_PRODUCTO { get; set; }
        [Required]
        [Display(Name = "Fabricación")]
        public int AÑO_FABRICACION { get; set; }
        [Required]
        [Display(Name = "Casa")]
        public string CASA_FABRICACION { get; set; }
        [Required]
        [Display(Name = "Estado")]
        public string ESTADO_PRODUCTO { get; set; }
        [Required]
        [Display(Name = "Area")]
        public string AREA_TRATAMIENTO { get; set; }
    }
}
