//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCTOS
    {
        public int ID_PRODUCTO { get; set; }
        public string DESC_PRODUCTO { get; set; }
        public int AÑO_FABRICACION { get; set; }
        public string CASA_FABRICACION { get; set; }
        public string ESTADO_PRODUCTO { get; set; }
        public string AREA_TRATAMIENTO { get; set; }
    }
}
